Guru/urls.py
from django.urls import path
from Guru import views

urlpatterns = [
    path("input/", views.input, name='tambah'),
    path("", views.index, name='guru'),
    path("nilai/", views.daftar, name="daftar_nilai")
]

Murid/urls.py
from django.urls import path
from . import urls
from Murid import views

urlpatterns = [
    path("", views.index, name="murid")
]

School/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.contrib.auth.views import LogoutView
from login import views as views_auth

urlpatterns = [
    path('admin/', admin.site.urls, name='administrator'),
    path('', include('social_django.urls', namespace='social')),
    path('', views_auth.index, name='login'),
    path('logadm/', views_auth.admin_login, name='admin_login'),
    path(
        'logout/',
        LogoutView.as_view(template_name=settings.LOGOUT_REDIRECT_URL),
        name='logout'
    ),
    url('adm/', include('Guru.urls')),
    url(r"^user/", include('Murid.urls')),

]

Guru/models.py
from django.db import models

# Create your models here.


class Soal(models.Model):
    sid = models.AutoField(primary_key=True)
    user_made = models.IntegerField()
    Soal = models.TextField(max_length=500)
    jawab1 = models.CharField(max_length=128)
    jawab2 = models.CharField(max_length=128)
    jawab3 = models.CharField(max_length=128)
    jawab4 = models.CharField(max_length=128)
    sbenar = models.CharField(max_length=128)

    class Meta:
        db_table = "soal"


class Kunci(models.Model):
    kid = models.AutoField(primary_key=True)
    A = models.CharField(max_length=20)
    B = models.CharField(max_length=20)
    C = models.CharField(max_length=20)
    D = models.CharField(max_length=20)

    class Meta:
        db_table = "kunci"

Murid/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    contest = models.TextField(blank=True, null=True)
    data = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

Guru/forms.py
from django import forms
from Guru.models import Soal


class SoalForm(forms.Form):
    user_made = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Masukkan Jawaban...', 'value': '', 'type': 'hidden', 'id': 'kodetugas'}))
    Soal = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Masukkan Soal...'}), required=True)
    jawab1 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Masukkan Jawaban...'}), required=True)
    jawab2 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Masukkan Jawaban...'}), required=True)
    jawab3 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Masukkan Jawaban...'}), required=True)
    jawab4 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Masukkan Jawaban...'}), required=True)
    isi = [('A', 'jawab1'), ('B', 'jawab2'), ('C', 'jawab3'), ('D', 'jawab4')]
    sbenar = forms.CharField(widget=forms.RadioSelect(choices=isi))


class SoalSave(forms.ModelForm):

    class Meta:
        model = Soal
        fields = ("__all__")

Guru/views.py
from django.shortcuts import render, redirect
from Guru.models import Soal
from Guru.forms import SoalForm, SoalSave

# Create your views here.


def input(request):

    if request.method == "POST":
        form = SoalSave(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/logadm')
    else:
        form = SoalForm
    return render(request, 'blog/admin/input.html', {'form': form})


def index(request):
    context = {
        'soal': Soal.objects.all()
        if request.user.is_authenticated else []
    }
    return render(request, 'blog/admin/index.html', {'data': context})


def daftar(request):
    return render(request, 'blog/admin/daftar_nilai.html')

Murid/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'blog/user/index.html')

login/views.py
from django.shortcuts import render
from .models import Post


def index(request):
    context = {
        'posts': Post.objects.order_by('-pk')
        if request.user.is_authenticated else []
    }

    return render(request, 'user_login.html', context)


def admin_login(request):
    context = {
        'posts': Post.objects.order_by('-pk')
        if request.user.is_authenticated else []
    }

    return render(request, 'admin_login.html', context)

templates/admin_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Admin BANK SOAL</title>
  <link rel="shortcut icon" href="{% static 'img/buku.png' %}" type="image/x-icon" />

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/animate.css' %}">

</head>

<body id="page-top">
  {% if user.is_authenticated %}
  {% if user.is_staff == 0 %}
  <script>
    document.location.href = "{% url 'murid' %}";
  </script>
  {% endif %}
  {% include 'navbar/admin_navbar.html' %}
  <!-- Topbar -->
  <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>

    <div class="ml-3 nav-item">
      <h1 class="h3 font-weight-bold mb-2 text-gray-800">
        {% block title %}
        {% endblock title %}</h1>
    </div>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

      <div class="topbar-divider d-none d-sm-block"></div>
      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.first_name}} {{user.last_name}} </span>
          <img class="img-profile rounded-circle center-cropped" width="60" src="{% static 'img/profiles/user.png' %}">
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Profile
          </a>
          <a class="dropdown-item" href="">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Settings
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
          </a>
        </div>
      </li>

    </ul>

  </nav>
  <!-- End of Topbar -->

  {% block body %} {% endblock body %}

  </div>
  <!-- Footer -->
  <footer class="sticky-footer bg-white shadow">
    <div class="container my-auto">
      <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Website 2020</span>
      </div>
    </div>
  </footer>
  <!-- End of Footer -->

  </div>
  <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>


  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <script>
    document.location.href = "{% url 'login' %}";
  </script>
  {% endif %}


  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %} "></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %} "></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/datatables-demo.js' %} "></script>
  <script>
    var rand = `{{user.id}}`
    $('#kodetugas').attr('value', rand)
  </script>

</body>

</html>

templates/admin_login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="{% static 'img/buku.png' %}" type="image/x-icon" />
  <title>Admin Bank Soal</title>
  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">
  {% if user.is_authenticated %}
    {% if user.is_staff == 0 %}
    <script>
      document.location.href = "{% url 'murid' %}";
    </script>
    {% else %}
    <script>
      document.location.href = "{% url 'guru' %}";
    </script>
    {% endif %}
  {% else %}
  <div class="container">
    <div class="row justify-content-center mt-5">
      <div class="col-md-8 mt-5">
        <div class="card bg-light p-3">
          <div class="card-body">
            <h1 class="text-center">LOGIN TO ADMIN BANK SOAL</h1>
            <div class="row mt-5">
              <div class="col-5">
                <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Login with Google
                </a>
              </div>
              <div class="col"></div>
              <div class="col-4 text-right">
                <a href="/" class="btn btn-primary">Login By User</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</div>


  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %} "></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %} "></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/datatables-demo.js' %} "></script>

</body>

</html>

templates/blog/admin/daftar_nilai.html
{% extends 'admin_base.html' %}

{% block title %}
Dafter Nilai
{% endblock title %}

{% block body %}

    <h1>Halo Semua</h1>

{% endblock body %}

templates/blog/admin/index.html
{% extends 'admin_base.html' %}

{% block title %}
Daftar Soal
{% endblock title %}

{% block body %}
<div class="container-fluid">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h5 class="m-0 font-weight-bold text-primary">Daftar Soal</h5>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Soal</th>
              <th scope="col">Pilihan</th>
              <th scope="col">Jawaban benar</th>
              <th scope="col">Aksi</th>
            </tr>
          </thead>
          <tbody>
          
            {% for dt in data.soal %}
            {% if dt.user_made == user.id %}
              <tr>
                <th scope="row">{{dt.sid}}</th>
                <td>{{dt.Soal}} </td>
                <td>
                  <ol type='A'>
                    <li>{{dt.jawab1}} </li>
                    <li>{{dt.jawab2}} </li>
                    <li>{{dt.jawab3}} </li>
                    <li>{{dt.jawab4}} </li>
                  </ol>
                </td>
                <td>{{dt.sbenar}} </td>
                <td class="text-white text-center">
                  <a class="btn badge badge-warning" href="#"><i class="fas fa-fw fa-edit"></i> Edit</a>
                  <a class="btn badge badge-danger" href="#"><i class="fas fa-fw fa-trash"></i> Delete</a>|
                </td>
              </tr>
            {% endif %}
            {% endfor %}
          </tbody>
        </table>
        <div class="mt-4">
          <a href="../adm/input" class="btn btn-outline-info"><i class="fas fa-fw fa-plus-square"> </i>Tambah Soal</a>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock body %}

templates/blog/admin/input.html
{% extends 'admin_base.html' %}

{% block title %}
Input Soal
{% endblock title %}

{% block body %}

<div class="container-fluid">
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h5 class="m-0 font-weight-bold text-primary">Input Soal</h5>
        </div>
        <div class="card-body p-4">
            <form method="POST" action="/adm/input/">
                {% csrf_token %}
                <!-- <div class="mb-3 text-danger">{{form.errors}}</div> -->
                <h5>Masukkan Soal: </h5>
                {{form.user_made}}
                <div class="mb-3">
                    {{ form.Soal}}
                </div>
                <p class="h5">Masukkan Semua Pilihan Jawaban !!</p>
                <div class="row mt-3">
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label for="id_jawab1" class="col-sm-2 col-form-label">Jawab1</label>
                            <div class="col-sm-10">
                                {{form.jawab1}}
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="id_jawab2" class="col-sm-2 col-form-label">Jawab2</label>
                            <div class="col-sm-10">
                                {{form.jawab2}}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group row">
                            <label for="id_jawab3" class="col-sm-2 col-form-label">Jawab3</label>
                            <div class="col-sm-10">
                                {{form.jawab3}}
                            </div>
                        </div>
                        <div class="form-group row mt-3">
                            <label for="id_jawab4" class="col-sm-2 col-form-label">Jawab4</label>
                            <div class="col-sm-10">
                                {{form.jawab4}}
                            </div>
                        </div>
                    </div>
                </div>
                <h5>Masukkan Jawaban Benar</h5>
                {{form.sbenar}}
                <div class="text-right mb-3">
                    <button type="submit" class="btn btn-info">Post</button>
                    <a href="/" class="btn btn-danger">Kembali</a>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock body %}

templates/blog/user/index.html
{% extends 'user_base.html' %} {% block body %}

<div class="container"></div>
{% endblock body %}

templates/navbar/admin_navbar.html
{% load static %}
<!-- Page Wrapper -->
<div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center" href="{% url 'guru' %}">
            <img class="rounded-circle img-profile float-left" src="{% static 'img/buku.png' %}" width="50" />
            <div class="sidebar-brand-text mx-3">Bank Soal</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">
        <!-- Heading -->
        <div class="sidebar-heading">
            <i class="fas fa-fw fa-book"></i>
            Soal
        </div>

        <!-- Nav Item - Dashboard -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'guru' %}">
                <i class="fas fa-fw fa-tachometer-alt"></i>
                <span>Dashboard</span></a>
        </li>


        <li class="nav-item mt-n3">
            <a class="nav-link" href="{% url 'tambah' %}">
                <i class="fas fa-fw fa-plus-square"></i>
                <span>Tambah Soal</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            <i class="fas fa-fw fa-book-open"></i>
            Nilai
        </div>

        <!-- Nav Item - Charts -->
        <li class="nav-item">
            <a class="nav-link" href="{% url 'daftar_nilai' %}">
                <i class="fas fa-fw fa-book-reader"></i>
                <span>Daftar Nilai</span></a>
        </li>
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>


    </ul>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

templates/user_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>User BANK SOAL</title>
  <link rel="shortcut icon" href="{% static 'img/buku.png' %}" type="image/x-icon" />

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">
  <link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">
  {% if user.is_authenticated %}
  {% if user.is_staff == 1 %}
    <script>
      document.location.href = "{% url 'guru' %}";
    </script>
  {% endif %}
  {% include 'navbar/admin_navbar.html' %}
<!-- Topbar -->
  <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>

    <div class="ml-3 nav-item">
      <h1 class="h3 font-weight-bold mb-2 text-gray-800">
      {% block title %}
      {% endblock title %}</h1>
    </div>
    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

      <div class="topbar-divider d-none d-sm-block"></div>
      <!-- Nav Item - User Information -->
      <li class="nav-item dropdown no-arrow">
        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
          <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.first_name}} {{user.last_name}} </span>
          <img class="img-profile rounded-circle center-cropped" width="60" src="{% static 'img/profiles/user.png' %}">
        </a>
        <!-- Dropdown - User Information -->
        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
          <a class="dropdown-item" href="">
            <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
            Profile
          </a>
          <a class="dropdown-item" href="">
            <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
            Settings
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
            <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
            Logout
          </a>
        </div>
      </li>

    </ul>

  </nav>
  <!-- End of Topbar -->

  {% block body %} {% endblock body %}

  </div>
  <!-- Footer -->
  <footer class="sticky-footer bg-white shadow">
    <div class="container my-auto">
      <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Website 2020</span>
      </div>
    </div>
  </footer>
  <!-- End of Footer -->

  </div>
  <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  
  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <script>
    document.location.href = "{% url 'login' %}";
  </script>
  {% endif %}


  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->
  <script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %} "></script>
  <script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %} "></script>

  <!-- Page level custom scripts -->
  <script src="{% static 'js/demo/datatables-demo.js' %} "></script>

</body>

</html>

templates/user_login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>LOGIN TO BANK SOAL</title>
  <link rel="shortcut icon" href="{% static 'img/buku.png' %}" type="image/x-icon" />

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">
  <div class="jumbotron">
    {% if user.is_authenticated %}
        {% if user.is_staff == 1 %}
        <script>
          document.location.href = "{% url 'guru' %}";
        </script>
        {% else %}
          <script>
          document.location.href = "{% url 'murid' %}";
        </script>
        {% endif %}
  {% else %}
    <div class="row justify-content-center">
      <div class="col-xl-7">
        <div class="card p-4">
          <div class="card-body">
            <h1 class="text-center">LOGIN TO BANK SOAL</h1>
            <div class="row mt-5  ">
              <div class="col-4">
                <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-google btn-user btn-block">
                  <i class="fab fa-google fa-fw"></i> Login with Google
                </a>
              </div>
              <div class="col"></div>
              <div class="col-4 text-right">
                <a href="logadm" class="btn btn-primary">Login By admin</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>


  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>

</html>